import "./globals.css";
import { Inter } from "next/font/google";
import { Poppins } from "next/font/google";

const poppins = Poppins({ weight: "400", subsets: ["latin"] });

export const metadata = {
  title: "JobShark",
  description: "Generated by JAWS",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} bg-jaws-white text-jaws-black  container mx-auto p-4`}
      >
        {children}
      </body>
    </html>
  );
}
